### Add Event Effect
POST http://localhost:8000/api/config/contracts/6422e76827a6ccc68c7ebd61/InvoiceCreated
Content-Type: application/json

{
    "accountId": "6423afbb93ccaf7e3effdda4",
    "amountField": "amount",
    "operation": "credit"
}

### Get Event Configuration
GET http://localhost:8000/api/config/contracts/6422e76827a6ccc68c7ebd61/InvoiceCreated

### Delete an Event Effect
DELETE http://localhost:8000/api/config/contracts/6422e76827a6ccc68c7ebd61/InvoiceCreated/6423afdd93ccaf7e3effdda9
