# List all accounts
GET http://localhost:8000/api/ledger/accounts
Content-Type: application/json

###

# Add an account
POST http://localhost:8000/api/ledger/accounts
Content-Type: application/json

{
  "name": "Account Receivable",
  "type": "asset"
}

###

# List all journal entries under the account
GET http://localhost:8000/api/ledger/accounts/6423afbb93ccaf7e3effdda4/journalEntries
Content-Type: application/json
