version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-replica
    restart: always
    command: --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
