###
# Create Asset
POST http://localhost:6000/createAsset
Content-Type: application/json

{
  "assetID": "asset4",
  "color": "blue",
  "size": 5,
  "owner": "Tom",
  "appraisedValue": 1000
}

###
# Transfer Asset
POST http://localhost:6000/transferAsset
Content-Type: application/json

{
  "assetID": "asset3",
  "newOwner": "Jerry"
}

###
# Read Asset
GET http://localhost:6000/readAsset?id=asset1

###
# Read All Assets
GET http://localhost:6000/readAllAssets

